[build]
  publish = "."
  functions = "netlify/functions"

# ---------- Redirect EVERYTHING on Netlify hosts to the apex (EXCEPT functions) ----------
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }

[[redirects]]
  from = "/*"
  to = "https://thecerfreport.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }

# ---------- Headers ----------
# Prod (custom domains): indexable
[[headers]]
  for = "/*"
  conditions = { Host = ["thecerfreport.com", "www.thecerfreport.com"] }
  [headers.values]
  X-Robots-Tag = "all"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Netlify hosts (including deploy previews): keep noindex (optional)
[[headers]]
  for = "/*"
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }
  [headers.values]
  X-Robots-Tag = "noindex"
