[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"   # good default; works with CommonJS or ESM

# --- keep functions on Netlify hosts (do NOT redirect these) ---
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }

# --- redirect everything else on netlify.app to the apex ---
[[redirects]]
  from = "/*"
  to   = "https://thecerfreport.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }

# ---------- Headers ----------
[[headers]]
  for = "/*"
  conditions = { Host = ["thecerfreport.com", "www.thecerfreport.com"] }
  [headers.values]
  X-Robots-Tag = "all"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*"
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }
  [headers.values]
  X-Robots-Tag = "noindex"
