[build]
  publish = "."
  functions = "netlify/functions"

# ---------- Handle API subdomain (no redirect for api.thecerfreport.com) ----------
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = { Host = ["api.thecerfreport.com"] }

# ---------- Allow functions on Netlify subdomain (IMPORTANT FIX) ----------
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }

# ---------- Redirect everything else on Netlify hosts to main domain ----------
[[redirects]]
  from = "/*"
  to = "https://thecerfreport.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }

# ---------- Headers ----------
[[headers]]
  for = "/*"
  conditions = { Host = ["thecerfreport.com", "www.thecerfreport.com", "api.thecerfreport.com"] }
  [headers.values]
  X-Robots-Tag = "all"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*"
  conditions = { Host = ["cerfreportnews.netlify.app", "*--cerfreportnews.netlify.app"] }
  [headers.values]
  X-Robots-Tag = "noindex"
