[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# --- Let serverless functions run (no redirect) on ALL hosts ---
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# --- Redirect the primary Netlify subdomain to the apex ---
[[redirects]]
  from = "https://cerfreportnews.netlify.app/*"
  to   = "https://thecerfreport.com/:splat"
  status = 301
  force = true

# --- Redirect deploy preview subdomains to the apex ---
# (matches URLs like https://deploy-preview-123--cerfreportnews.netlify.app/...)
[[redirects]]
  from = "https://*--cerfreportnews.netlify.app/*"
  to   = "https://thecerfreport.com/:splat"
  status = 301
  force = true

# ---------- Headers ----------
# NOTE: Netlify's headers in TOML don't support host conditions.
# If you need host-specific headers, keep them simple or apply via your CDN/DNS.
[[headers]]
  for = "/*"
  [headers.values]
  X-Robots-Tag = "all"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; prel
