[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# OPTIONAL: pretty alias to your function (use this if you want /add-link)
[[redirects]]
  from = "/add-link"
  to   = "/.netlify/functions/add-link"
  status = 200

# Global headers
[[headers]]
  for = "/*"
  [headers.values]
  X-Robots-Tag = "all"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
