[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "https://cerfreportnews.netlify.app/*"
  to   = "https://thecerfreport.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://*--cerfreportnews.netlify.app/*"
  to   = "https://thecerfreport.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://cerfreportnews.netlify.app"
  to   = "https://thecerfreport.com"
  status = 301
  force = true

[[redirects]]
  from = "https://*--cerfreportnews.netlify.app"
  to   = "https://thecerfreport.com"
  status = 301
  force = true
